apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-default
  namespace: openshift-ingress
spec:
  template:
    spec:
      containers:
        - name: router
          env:
          - name: ROUTER_SUBDOMAIN
            value: ${name}-${namespace}.apps.192.168.1.165.nip.io
          - name: ROUTER_ALLOW_WILDCARD_ROUTES
            value: "true"
          - name: ROUTER_OVERRIDE_HOSTNAME
            value: "true"
